// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlW8mJiBsR5UwHw8bmg2OsJQPSoFGx8s',
    appId: '1:609107762959:web:5edc24eb507d76c5a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    authDomain: 'plis-b0c7c.firebaseapp.com',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK3Xnt43_qtM8fgpdsRfDYcaGxhlR70TA',
    appId: '1:609107762959:android:aff3096fbf1a001aa3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpmn7X2KglhVILPpMNi8mYoJ6lEEE0q0',
    appId: '1:609107762959:ios:a4723cabbdcb4248a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
    iosBundleId: 'com.example.plisAdministrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpmn7X2KglhVILPpMNi8mYoJ6lEEE0q0',
    appId: '1:609107762959:ios:a4723cabbdcb4248a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
    iosBundleId: 'com.example.plisAdministrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlW8mJiBsR5UwHw8bmg2OsJQPSoFGx8s',
    appId: '1:609107762959:web:9172e14f0a5e60b5a3a87a',
    messagingSenderId: '609107762959',
    projectId: 'plis-b0c7c',
    authDomain: 'plis-b0c7c.firebaseapp.com',
    storageBucket: 'plis-b0c7c.firebasestorage.app',
  );
}
